version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: universal
      POSTGRES_USER: giacomo
      POSTGRES_PASSWORD: giacomo
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
