services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - './postgres-data:/var/lib/postgresql/data'  # persistente anche se spegni
    environment:
      - POSTGRES_USER=giacomo
      - POSTGRES_PASSWORD=giacomo
      - POSTGRES_DB=universal