-- PROCEDURE

-- TRASFORMA UNO STUDENTE IN UN EX_STUDENTE
CREATE OR REPLACE PROCEDURE studentToExStudent (
    _id uuid,
    _motivo TipoMotivo
)
  LANGUAGE plpgsql
  AS $$
    BEGIN

        UPDATE universal.utenti
        SET tipo = 'ex_studente'
        WHERE universal.utenti.id = _id;

        INSERT INTO universal.ex_studenti (id, motivo)
        VALUES (_id, _motivo);

        DELETE FROM universal.studenti
        WHERE universal.studenti.id = _id;

    END;
  $$;

-- GENERA MAIL UTENTE DATO NOME COGNOME E TIPO

-- MODIFICA PASSWORD STUDENTE

-- ISCRIZIONE APPELLO STUDENTE

-- DISISCRIZIONE APPELLO STUDENTE

-- ISCRIZIONE CORSO DI LAURERA STUDENTE

-- DISISCRIZIONE CORSO DI LAUREA STUDENTE

-- CREAZIONE APPELLO DOCENTE

 -- CANCELLAZIONE APPELLO DOCENTE

-- CREAZIONE UTENTE SEGRETARIO

-- CANCELLAZIONE STUDENTE SEGRETARIO

-- ASSEGNAZIONE DOCENTE INSEGNAMENTO SEGRETARIO

-- DISASSEGNAMENTO DOCENTE INSEGNAMENTO SEGRETARIO

-- SEGRETARIO CREA NUOVO STUDENTE

-- SEGRETARIO CREA NUOVO DOCENTE

-- SEGRETARIO MODIFICA STUDENTE

-- SEGRETARIO MODIFICA DOCENTE

-- SEGRETARIO MODIFICA CALENDARIO APPELLI

-- SEGRETARIO CREA NUOVO SEGRETARIO

-- SEGRETARIO MODIFICA SEGRETARIO

-- SEGRETARIO CANCELLA SEGRETARIO

-- SEGRETARIO CREA PASSWORD UTENTE

-- SEGRETARIO CREA CORSO DI LAUREA

-- SEGRETARIO MODIFICA CORSO DI LAUREA

-- SEGRETARIO ELIMINA CORSO DI LAUREA

-- SEGRETARIO CREA NUOVO INSEGNAMENTO

-- SEGRETARIO MODIFICA NUOVO INSEGNAMENTO

-- SEGRETARIO ELIMINA INSEGNAMENTO

-- SEGRETARIO CREA APPELLO

-- SEGRETARIO MODIFICA APPELLO

-- SEGRETARIO ELIMINA APPELLO

-- SEGRETARIO ISCRIVE UNO STUDENTE AD UN APPELLO

-- SEGRETARIO ELIMINA STUDENTE DA UN APPELLO