version: '3.1'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "postgres://giacomo:giacomo@db:5432/universal"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: universal
      POSTGRES_USER: giacomo
      POSTGRES_PASSWORD: giacomo
    ports:
      - "5432:5432"
